use test;
CREATE SCHEMA APP;
USE APP;


CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID int NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME varchar(255) NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE APPLICATIONS(
APPLICATION_ID int NOT NULL AUTO_INCREMENT,
APPLICATION_NAME varchar(255) NOT NULL,
 DEPARTMENT_ID int NOT NULL ,
 PRIMARY KEY (APPLICATION_ID),
 FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
 );
 
CREATE TABLE FILE_TYPES(
 FILE_TYPE_ID INT NOT NULL AUTO_INCREMENT,
 FILE_TYPE VARCHAR(255) NOT NULL,
 PRIMARY KEY (FILE_TYPE_ID)
);

CREATE TABLE DRIVERS (
    DRIVER_ID int NOT NULL AUTO_INCREMENT,
	DRIVER_NAME varchar(255) NOT NULL,
    PRIMARY KEY (DRIVER_ID)
);

CREATE TABLE PLATFORMS (
    PLATFORM_ID int NOT NULL AUTO_INCREMENT,
	PLATFORM_NAME varchar(255) NOT NULL,
    PRIMARY KEY (PLATFORM_ID)
);

CREATE TABLE MESSAGE_TYPES (
    MESSAGE_TYPE_ID int NOT NULL AUTO_INCREMENT,
	MESSAGE_TYPE_NAME varchar(255) NOT NULL,
    PRIMARY KEY (MESSAGE_TYPE_ID)
);



CREATE TABLE LOCATORS(
 LOCATOR_ID INT NOT NULL AUTO_INCREMENT,
 IID VARCHAR(500) NOT NULL UNIQUE,
 LOCATOR_VALUE VARCHAR(10000) NOT NULL,
 AUTHOR VARCHAR(1000),
 TIME_STAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 DESCRIPTION VARCHAR(2000),
 LOGS VARCHAR(30000) DEFAULT '',
 LOCATOR_TYPE VARCHAR(250) NOT NULL,
 DRIVER_TYPE VARCHAR(255) NOT NULL,
 APPLICATION_ID INT NOT NULL,
 FILE_TYPE_ID INT NOT NULL,
 PRIMARY KEY (LOCATOR_ID),
 FOREIGN KEY (FILE_TYPE_ID) REFERENCES FILE_TYPES(FILE_TYPE_ID),
 FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID)
 );
 
 
CREATE TABLE MESSAGES(
 MESSAGE_ID INT NOT NULL AUTO_INCREMENT,
 IID VARCHAR(500) NOT NULL UNIQUE,
 MESSAGE_TEXT VARCHAR(2000) NOT NULL,
 IS_CLIENT_MESSAGE BOOLEAN DEFAULT FALSE,
 AUTHOR varchar(1000) NOT NULL,
 TIME_STAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 DESCRIPTION VARCHAR(2000),
 LOGS VARCHAR(10000) DEFAULT '', 
 APPLICATION_ID INT NOT NULL,
 FILE_TYPE_ID INT NOT NULL, 
 PRIMARY KEY (MESSAGE_ID),
 FOREIGN KEY (FILE_TYPE_ID) references FILE_TYPES(FILE_TYPE_ID),
 FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID)
 );
 
 
 
CREATE TABLE QUERIES (
 QUERY_ID INT NOT NULL AUTO_INCREMENT,
 IID VARCHAR(500) NOT NULL UNIQUE,
 IS_ACTIVE BOOLEAN DEFAULT FALSE NOT NULL,
 QUERY_STRING VARCHAR(1000) NOT NULL, 
 DB_DATA_TYPE_ARRAY VARCHAR(1000) NOT NULL,
 QUERY_TYPE VARCHAR(1000) NOT NULL,
 VENDOR_TYPE VARCHAR(1000) NOT NULL,
 AUTHOR VARCHAR(1000) NOT NULL,
 TIME_STAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 DESCRIPTION VARCHAR(2000),
 LOGS VARCHAR(10000) DEFAULT '', 
 APPLICATION_ID INT NOT NULL,
 FILE_TYPE_ID INT NOT NULL,
 PRIMARY KEY (QUERY_ID),
 FOREIGN KEY (FILE_TYPE_ID) references FILE_TYPES(FILE_TYPE_ID),
 FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID)
 );
 
 CREATE TABLE USERS(
  USER_ID INT NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD_TEXT VARCHAR(1000) NOT NULL ,
  ROLE VARCHAR(30) NOT NULL,
  PRIMARY KEY (USER_ID) 
 );
 
 
 
DROP TABLE LOCATORS;
DROP TABLE MESSAGES;
DROP TABLE QUERIES;
DROP TABLE USERS;
 
 
 
 
 
 
 
 
 
 





 